---
- name: Create ec2 instance
  hosts: local
  connection: local
  vars:
    instance_type: t2.micro
    image: ami-04781752c9b20ea41
    security_group_name: SSH-HTTP
    vpc_ip: default
    vpc_subnet_id: default
    region: us-east-2
    keypair: devops_10_ubuntu


  tasks:
    - name: Create security group
      ec2_group:
        name: "{{ security_group_name }}"
        description: Webserver security group
        region: "{{ region }}"
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
        rules:
          - proto: tcp
            from_port: 22
            to_port: 22
            cidr_ip: 0.0.0.0/0
        rules_egress:
          - proto: tcp
            from_port: 8080
            to_port: 8080
            cidr_ip: 0.0.0.0/0
    - name: new ec2 instance
      ec2:
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key "
        group: "{{ security_group_name }}"
        instance_type: "{{ instance_type }}"
        image: "{{ image }}"
        wait: true
        region: "{{ region }}"
        keypair: "{{ keypair }}"
        count: 1
      register: ec2
    - name: add new instance to hosts file
      add_host:
        name: "{{ item_public_ip }}"
        groups: webserver
      with_items: "{{ ec2_instances }}"