---
- name: Create ec2 instance
  hosts: local
  connection: local
  vars:
    instance_type: t2.micro
    image: ami-04781752c9b20ea41
    security_group_name: SSH-HTTP
    vpc_ip: default
    vpc_subnet_id: default
    region: us-east-2



  tasks:
    - name: create key
      ec2_key:
        name: aws-ansible-test
        region: "{{ region }}"
      register: ec2_key_result
    - name: save private key
      copy:
        content: "{{ ec2_key_result.key.provate_key }}"
        dest: ./aws-ansible-test.pem
        mode: 0600
      when: ec2_key_result.changed
    - name: Create security group
      ec2_group:
        name: "{{ security_group_name }}"
        description: Webserver security group
        region: "{{ region }}"
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
        rules:
          - proto: tcp
            from_port: 22
            to_port: 22
            cidr_ip: 0.0.0.0/0
          - proto: tcp
            from_port: 80
            to_port: 80
            cidr_ip: 0.0.0.0/0
        rules_egress:
          - proto: all
            cidr_ip: 0.0.0.0/0
    - name: new ec2 instance
      ec2:
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
        group: "{{ security_group_name }}"
        instance_type: "{{ instance_type }}"
        image: "{{ image }}"
        wait: true
        region: "{{ region }}"
        keypair: "{{ keypair }}"
        count: 1
        user_data:
          |
          #!/bin/bash
          sudo apt update
          sudo apt install python nginx -y
          sudo service nginx start
          sudo service nginx enabled
      register: ec2
    - name: update inventory
      add_host:
        hostname: "{{ ec2.instances[0].public_ip }}"
        groups: webserver
      delegate_to: localhost

    - name: wait for ssh
      wait_for:
        host: "{{ item.public_ip }} "
        port: 22
        state: started
      with_items: "{{ ec2.instances }}"
    - name: wait for 120 sec
      wait_for:
        timeout: 120
      delegate_to: localhost
- name: copy new index.html
  hosts: webserver
  remote_user: ubuntu
  vars:
    ansible_ssh_private_key_file: ./aws-ansible-test.pem
  become: yes
  tasks:
    - name: copy index.html
      copy:
        src: ./index.html
        dest: /var/www/html
    - name: restart nginx
      service:
        name: nginx
        state: restarted
